### ISSUE TITLE
Invalid value definition

### ISSUE THREAD

**Issue by RadekDvorak** [Andrewsville/PHP-Token-Reflection#38]
Apigen fails and blames  TokenReflection library. It states the cause of the exception was:

'"Invalid value definition." was the T_WHITESPACE token (line 28) in following part of SomeClass::ACCESS_DEPRECATED source code'.

The reported line looks like '        const ACCESS_DEPRECATED = '3' ;' (tab indents, space after the constant value before the semicolon). Removing the space after the constant value helps as a workaround.

See the stacktrace: https://gist.github.com/1865268

**Comment by Andrewsville** [comment]
Thanks for the report. The issue should be fixed by fec7a2f5461c49b618734a06a3d11366bd1944b4. The fix will be included in the next release.
