### ISSUE TITLE
Add support for parsing Doctrine annotations

### ISSUE THREAD

**Issue by lisachenko** [Andrewsville/PHP-Token-Reflection#41]
Many projects use doctine annotations to store metadata for class, however ApiGen doesn't support such format, for example, in Symfony2 there is Route annotation `@Route("/index", defaults={"_format" = "json"})`

Can you add a support for `@Annotation` annotation in class to use such classes for storing metadata ang show this information in generated documentation?

**Comment by Andrewsville** [comment]
I don't believe this is not something TokenReflection should handle (it is able to return the @annotation tag and its value but it does no try to parse the value). However we plan to support Doctrine annotations via an official ApiGen plugin apigen/apigen#36. The bad news is that there is no estimate when it will be ready :(
